### ISSUE TITLE
Why Buble, but not Babel?

### ISSUE THREAD

**Issue by ghost** [kbrsh/moon-template#2]
Can you tell me why you chosen Buble instead of Babel?

**Comment by kbrsh** [comment]
It's much easier to get started with. I can switch over to Babel if that's what is preferred.

**Comment by ghost** [comment]
@kbrsh, I think it's good idea to do separated template for Babel =) 
I would try , lol

**Comment by kbrsh** [comment]
Haha I can definitely switch this template to use Babel and Webpack.

**Comment by ghost** [comment]
But there is no Webpack loader for Moon files... I had written something, but I'm not sure it's works properly. But it seems to work

**Comment by ghost** [comment]
Lol. It's works

**Comment by ghost** [comment]
But CSS not works :( I don't got how to make it work

**Comment by kbrsh** [comment]
Haha I'll definitely work on a plugin. It should be simple enough. The problem is that `moonify` automatically emits global styles which are added by a plugin.

**Comment by ghost** [comment]
ayy lmao

**Comment by kbrsh** [comment]
The template now uses Babel.
